Patch 2
CircleCI-Public/continuation-orb pull request #11
Opened 2021-06-28 10:28 UTC by aaronfox1

Helping Kyle and CPE with some orb maintenance. Adding suggestion from issue 2.

2021-08-18 10:45 UTC, gmemstr approved these changes

2021-08-20 17:46 UTC, KyleTryon commented
Changed to a major change. Holding for a moment as it would be ideal to include other major changes at the same time.

2021-08-20 18:54 UTC, KyleTryon commented
@salilsu A major version change here would designate a 1.0.0 release. My previous patch change just merged updated the description and usage examples so I believe it is good. Is this alright with you?

2021-08-21 00:09 UTC, salilsu commented
I'd like to get a second opinion from @sulami but it looks good to me.

2021-08-25 09:55 UTC, sulami approved these changes

2021-08-25 09:55 UTC, sulami commented on src/commands/continue.yml
> +  tag:
\~ I'd maybe be more specific here and call it `image_tag` or something like that, otherwise `tag` can be slightly ambiguous in this context.

2021-08-31 18:30 UTC, brivu requested changes
Hi there!  

I'm Brian from the CircleCI Community and Partner Engineering team.  After looking through your changes, you included the Docker image in your command (lines 22 -23) which is invalid.  The executor can only be included under jobs and not commands.   

We'll take a look over your code again after you've made the changes.  

Thanks! 
Brian

2023-06-20 15:13 UTC, Fernando-Abreu commented
Closing this since due to inactivity

2023-06-20 15:13 UTC, closed without merging